### ISSUE TITLE
Incorrect explanation in Layout container example

### ISSUE THREAD

**Issue by leoasis** [vasanthk/react-bits#10]
Hi! First of all wanted to say thank you for contributing such an great set of resources and information about React stuff. Awesome job!

Still haven't finished reading all of the content in the repo, but when I read the example in https://github.com/vasanthk/react-bits/blob/master/13.layout-container.jsx, I found some incorrect information regarding the optimization that can be made there.

It says: 
```js
// While HorizontalSplit will be parent to both components, it will never be their owner.
// We can tell it to update never, without interrupting the lifecycle of the components inside.
```

This in fact won't work as it is explained there. The reconciliation in React does not depend on the elements being owners or not. If the `HorizontalSplit` component doesn't render, its content won't update either, it doesn't matter if the elements were received via props or created by the component directly.

You can try that in this fiddle I created: https://jsfiddle.net/69z2wepo/74765/

I don't think there's a good way to tell React that a component is static and avoid its reconciliation. At least not a straight forward way.

Maybe that pattern should not talk about perf improvements and only about splitting layout vs content components, which is a good idea by itself anyway?

**Comment by vasanthk** [comment]
@leoasis Good catch!
Mind sending in a PR modifying it to describe more about splitting layout vs content components?

**Comment by leoasis** [comment]
@vasanthk took a stab at it, let me know what you think 😄

**Comment by leoasis** [comment]
Thanks for accepting my PR @vasanthk 😄
