### ISSUE TITLE
It would be interesting to see correspond eslint-react rules corresponding to the good/bad examples in this repo

### ISSUE THREAD

**Issue by davidfurlong** [vasanthk/react-bits#11]

**Comment by vasanthk** [comment]
@davidfurlong Sounds like a great idea 😄 
Would you like to take a stab at it?

**Comment by davidfurlong** [comment]
@vasanthk I'm afraid I'm very short on time at the moment. Perhaps when things ease off a little

**Comment by vasanthk** [comment]
@davidfurlong Closing this for now. Would be really cool to have this though.
Let us know if you ever get on this :)
