### ISSUE TITLE
gitbook link gives 401 unauthorized error

### ISSUE THREAD

**Issue by honungsburk** [vasanthk/react-bits#112]
When I click on the link https://vasanthk.gitbooks.io/react-bits/content/ I expect to be taken to the content. Instead, I get a 401 Unauthorized error.

**Comment by vasanthk** [comment]
@honungsburk Apologies for the late response. 
Looks to be working. Do you still see this issue? Please re-open this issue if so.

**Comment by Dee-OGCIO** [comment]
Problem occurs (again?):
https://data-dot-one.gitbooks.io/ckan-api-development-guide/content/en/

401 Unauthorized

Likely what's the cause ?
Thanks !

**Comment by Mohsin0582** [comment]
Unauthorized access and the verification link I received wants my cnic to
be uploaded, which I am not willing to share.
