### ISSUE TITLE
ReadMe Redirection Links not working

### ISSUE THREAD

**Issue by Pragnesh2208** [vasanthk/react-bits#115]
as title suggest , we should consider to update readme file links as latest PR changes

**Comment by cosn** [comment]
I have a simple PR to fix this, but need permissions to publish branch @vasanthk

**Comment by vasanthk** [comment]
Thnk you for raising this. @cosn Are you able to send a PR with your changes?

**Comment by vasanthk** [comment]
Fixed it, Thank you for bringing this up.
