### ISSUE TITLE
Use markdown for easier reading

### ISSUE THREAD

**Issue by ralphite** [vasanthk/react-bits#22]
Most of the code are not runnable. Instead of using JSX, please use markdown for easier reading.

**Comment by vasanthk** [comment]
@ralphite There is a PR in progress for this https://github.com/vasanthk/react-bits/pull/15 by @Reda-bx

**Comment by vasanthk** [comment]
@ralphite The gitbook version can be accessed [here](https://vasanthk.gitbooks.io/react-bits)
Thanks for the idea :)
