### ISSUE TITLE
Not issues~

### ISSUE THREAD

**Issue by wangcongyi** [vasanthk/react-bits#28]
#### modify the tagname according to the parameter
```js
    const Wrap = ({ tagName, content }) => { 
      const Tag = `${tagName}`     // variable name must begin with capital letters
      return <Tag>{content}</Tag>
    }
````

**Comment by vasanthk** [comment]
@wangcongyi Added a small note to the Weapper components section. Let me know if it looks fine.

**Comment by wangcongyi** [comment]
@vasanthk  It looks great 
I apologize for my laziness
Happy coding
