### ISSUE TITLE
Gitbook

### ISSUE THREAD

**Issue by Reda-bx** [vasanthk/react-bits#3]
it would be awesome if this was made with gitbook, easey to ready/navigate... is there any possibility to make this a gitbook doc?

**Comment by kubens** [comment]
+1

**Comment by vasanthk** [comment]
@Reda-bx Good idea. Let me check it out.
Does Gitbook work well for just code as well?
Mostly seen them for docs which have a lot of text in them.

**Comment by Reda-bx** [comment]
@vasanthk unfortunately no, we will need to put the code inside a .markdown file... I can work on that, just ping me.

**Comment by vasanthk** [comment]
@Reda-bx Thanks. Happy to accept any related PRs :)

**Comment by bmeverett** [comment]
I can take a look at this as well. A lot of conversions. Do you want to keep the original `.jsx` files or just convert them straight to markdown?

**Comment by vasanthk** [comment]
Thank you @bmeverett @Reda-bx 🎉  This is amazing!!
We could delete the JSX eventually when all of them have been moved to MDs.

**Comment by atakangktepe** [comment]
Yes, sounds good 🎉 I can contribute while converting to gitbook.

**Comment by vasanthk** [comment]
Yeyy 🎉 🎉 🎉 🎉

**Comment by Reda-bx** [comment]
@bmeverett yeah, I did convert all the jsx files to md files #15
