### ISSUE TITLE
“Conventions” reflect neither community conventions nor React team recommendations

### ISSUE THREAD

**Issue by gaearon** [vasanthk/react-bits#37]
Hey! Thanks for your work on creating learning material in this repo.

I think the list of “conventions” is highly subjective right now. The React team never advocated any of them, and in fact I think the team would disagree with some:

* https://github.com/vasanthk/react-bits/blob/master/conventions/02.adding-class-names.md: It's fine to use arrays if you'd like.
* https://github.com/vasanthk/react-bits/tree/master/conventions: There is nothing bad at all about using methods!
* https://github.com/vasanthk/react-bits/blob/master/conventions/05.use-html-entities.md: `String.fromCharCode()` is not “React’s”, and also not an “HTML entity” (that’s a different thing). And I don’t quite understand why this is recommended here (what is the difference?)
* https://github.com/vasanthk/react-bits/blob/master/conventions/08.closures-in-render.md: It won’t matter in many cases, and the advice doesn’t really explain how to bind methods.
* https://github.com/vasanthk/react-bits/blob/master/conventions/09.functional-components.md: I would not recommend to rely on hoisting because it is confusing.
* https://github.com/vasanthk/react-bits/blob/master/conventions/10.formatting-props.md: This is just a style opinion.
* https://github.com/vasanthk/react-bits/blob/master/conventions/11.super-in-constructor.md: We actually recommend using `super(props)` if you define constructor because somebody reading that code later might be surprised that `this.props` doesn’t work.

It would be great to separate author’s stylistic preferences from correctness advice (e.g. about `tbody`) and clearly label it as such. Those are not React community’s conventions, nor are they recommended by React team.

**Comment by vasanthk** [comment]
Thanks for the clarification, @gaearon.
I agree it was a bit opinionated, deleted the section for now. Will update some of your inputs into the section.

**Comment by gaearon** [comment]
Thanks!
