### ISSUE TITLE
Why can’t use regular if/else conditions inside a component definition?

### ISSUE THREAD

**Issue by F3n67u** [vasanthk/react-bits#5]
In Section [Conditional Rendering](https://github.com/vasanthk/react-bits/blob/master/04.conditional-rendering.jsx), It says:
> You can’t use regular if/else conditions inside a component definition. The conditional (ternary) operator is your friend.

I think it is wrong. Because instead of
```
// if- else (big blocks)
function render() {
  return condition ? (
    <span>
    Rendered when `truthy`
  </span>
  ) : (
    <span>
    Rendered when `falsey`
  </span>
  )
}
```
this render function can also be written in a if/else way:
```
function render() {
  if (condition) {
    return  (
      <span>
        Rendered when `truthy`
      </span>
    )
  }
  else {
    return  (
      <span>
        Rendered when `falsey`
      </span>
    )
  }
}
```

**Comment by delanni** [comment]
Yes, I assume you can. What's the issue here?

**Comment by F3n67u** [comment]
@delanni Sorry. I didn't say it clearly. I have already updated my comment.

**Comment by amsheehan** [comment]
Though it will technically work, you'd probably want to extract a function to do this (pretty ugly otherwise). I think the most mileage you'll get out of ternarys as they apply to conditional rendering is when you are branching _inside_ of a block of JSX, where 'if/else' truly will not work.

**Comment by vasanthk** [comment]
@F3n67u You're right. Sorry, it was a typo. Fixed it now.
**You can use regular if/else conditions inside a component definition.**
As @amsheehan  pointed out - as the render function markup gets larger it is always advisable to split it up into logically smaller components and compose them.
