### ISSUE TITLE
Misleading Anti-Patterns

### ISSUE THREAD

**Issue by mocheng** [vasanthk/react-bits#53]
In my understanding, titles of  [Refs over findDomNode()](https://github.com/vasanthk/react-bits/blob/master/anti-patterns/02.refs-over-findDOMNode.md) and [HOC over mixins](https://github.com/vasanthk/react-bits/blob/master/anti-patterns/03.HOC-over-mixins.md) in **anti-patterns** are actually **preferred patterns**. These two titles looks so weird in **Anti-Patterns** sections. 

It must be titled as **findDomNode over Refs** and **mixins over HOC** to be anti-patterns and consistent with other parts.

**Comment by Nathan-Schwartz** [comment]
I agree that the wording could be improved. Personally, I think that titling them `findDomNode` and `mixins` would be even more clear.

**Comment by vasanthk** [comment]
@mocheng @Nathan-Schwartz Fixed.
