### ISSUE TITLE
Best practices for role-based UI

### ISSUE THREAD

**Issue by Sunil6591** [vasanthk/react-bits#57]
Its fantastic list so far, i have being following it very closely. However, recently i have being struck with role-based implementation in react. Any thoughts on this you came across?

**Comment by Nathan-Schwartz** [comment]
@Sunil6591 Can you explain a bit more what you mean by role-based implementation? Are you talking about conditional rendering based on something such as user role?

**Comment by Sunil6591** [comment]
Here is the flow - 
Get the custom authorizations/roles from logged-in token, e.g. jwt
Based on these authorizations/roles, do conditional rendering.
Also do the same check while calling actions on redux.

**Comment by misha-pachin** [comment]
@Sunil6591 This sounds like you should be able to handle such workflow through container component, which will contain all the logic - it'll look at the token and provide callbacks to children component through props and/or it'll contain conditional rendering as you said.

- [Container Component](https://github.com/vasanthk/react-bits/blob/master/patterns/14.container-component.md)
- [Presentational and Container components](https://github.com/vasanthk/react-bits/blob/master/patterns/25.presentational-vs-container.md)

It should be mentioned that you also could use custom Utils which will be awailable in global object or context wrapper - and your containers will use it and retrieve relevant info from it to get current logged-in role.
- [Context Wrapper](https://github.com/vasanthk/react-bits/blob/master/patterns/21.context-wrapper.md)
