### ISSUE TITLE
Remove plagiarized content

### ISSUE THREAD

**Issue by chantastic** [vasanthk/react-bits#66]
This is a dupe of https://github.com/vasanthk/react-bits/issues/21.

The issue is not resolved. The delay was on account of my father passing away. Obviously this is a decidedly less important issue. However, I will do my best to file the appropriate paperwork this week.

This issue of plagiarism for this repo and all forks remains an open issue.

**Comment by vasanthk** [comment]
@chantastic Sorry to hear about your dad.
I did not hear back from you for months, so let it be there. The attributions were moved to a different section while the repo was converted from js -> md files.
Anyways, I have removed the files in question as per request.
