### ISSUE TITLE
[Using Indexes as Key] Misleading information 

### ISSUE THREAD

**Issue by Nathan-Schwartz** [vasanthk/react-bits#67]
Anti-patterns' [Using Indexes as key](https://github.com/vasanthk/react-bits/blob/master/anti-patterns/06.using-indexes-as-key.md) section is based on an outdated article and is no longer correct.

>Keys should be stable, predictable, and unique. Unstable keys (like those produced by Math.random()) will cause many component instances and DOM nodes to be unnecessarily recreated, which can cause performance degradation and lost state in child components. 
>- [React docs](https://facebook.github.io/react/docs/reconciliation.html#tradeoffs)

A more entertaining explanation can be found [here](https://youtu.be/-t8eOoRsJ7M?t=1037) (credit to Lin Clark).

Suggestions:
- replace the blog link with a link to the React docs
- remove the "Even Better" section
- rename the "Better" section title to "Good"
- add an explanation how `obj.id` should be unique and repeatable among all siblings

@vasanthk I'm happy to open a PR for this, if you are satisfied with the suggestions I made 👍

**Comment by vasanthk** [comment]
@Nathan-Schwartz Thank you for this. Happy to accept a PR :)
