### ISSUE TITLE
Some confusions on the anti-patterns

### ISSUE THREAD

**Issue by Magellol** [vasanthk/react-bits#7]
Hey,

I feel we should add more clarity on the anti pattern bits.
For instance, in the [refs over findDOMNode()](https://github.com/vasanthk/react-bits/blob/master/anti-patterns/02.refs-over-findDOMNode.jsx), in the code comments, it's saying: `Use findDOMNode() over callback refs` which is kind of stating you should use `findDOMNode` over `refs`, although after reading the [references](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220), it's clearly the opposite we should do.

Although on the [HOC over Mixins example](https://github.com/vasanthk/react-bits/blob/master/anti-patterns/03.HOC-over-mixins.jsx) (and that's where I think there is some confusion), it's saying `Use Higher order components over Mixins`, which this time is the right approach.

How do you feel about choosing one or the other approach but staying consistent? I'd suggest saying something like `Use "this" over "that"` kind of structure.

**Comment by vasanthk** [comment]
@Magellol You're right. Accidentally, typed the other way round.
I'll fix it. Thanks :)
