### ISSUE TITLE
Is it OK to fork it and translate into other language by myself?

### ISSUE THREAD

**Issue by hateonion** [vasanthk/react-bits#85]

**Comment by vasanthk** [comment]
You are most welcome to. Please do send in a PR to the main repo readme once done. I shall link it :)

**Comment by hateonion** [comment]
Hi, @vasanthk Still trying to figure it out what's the best way to share my translation. I've translated `Conditional in JSX` and `Async Nature Of setState()`  
https://github.com/hateonion/react-bits and pushed to my forked repo. But seems I will override the original stuff. Am thinking 2 approaches,

1. Still work on my forked repo, but create a CN-Zh folder and restructure it in that folder, then send pr to the master repo.
2. I will create another repo and push my translation in that repo. Once I finish it, I will send a pr to update the Readme and attach my repo link. 

Which one would you prefer?

**Comment by vasanthk** [comment]
@hateonion Number 2 sounds fine. 
In the past, for [js-bits](https://github.com/vasanthk/js-bits) a contributor did it that way.
Might be easier for you to create your own gitbook as well similar to https://vasanthk.gitbooks.io/react-bits

**Comment by hateonion** [comment]
Cool Thanks Man
